version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: dns-tracker-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: redis-server --appendonly yes --appendfsync everysec

  golang-server:
    build: .
    container_name: dns-tracker-go
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=""
      - REDIS_DB=0
      - REDIS_TIMEOUT=5
    volumes:
      - ./config.yml:/app/config.yml
    depends_on:
      - redis
